# Generated by Django 2.1.5 on 2020-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_s', models.CharField(max_length=100)),
                ('spec_s', models.CharField(max_length=100)),
                ('material_s', models.CharField(max_length=100)),
                ('rating_s', models.CharField(blank=True, max_length=100, null=True)),
                ('size1_s', models.IntegerField(blank=True, null=True)),
                ('sch1_s', models.IntegerField(blank=True, null=True)),
                ('size2_s', models.IntegerField(blank=True, null=True)),
                ('sch2_s', models.IntegerField(blank=True, null=True)),
                ('facing_s', models.CharField(blank=True, max_length=100, null=True)),
                ('qty_s', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
