# Generated by Django 2.1.5 on 2020-06-09 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADNOC_documentno', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('revision', models.CharField(blank=True, max_length=5, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('transmittal_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_of_issue', models.CharField(choices=[('IFA', 'IFA'), ('IFI', 'IFI')], default='IFA', max_length=3, null=True)),
                ('document', models.FileField(blank=True, upload_to='documents/%Y/%m/%d')),
                ('aprroval_date', models.DateField(blank=True, null=True)),
                ('receipt_transmittalno', models.CharField(blank=True, max_length=100, null=True)),
                ('view_response', models.FileField(blank=True, null=True, upload_to='')),
                ('aprroval_code', models.CharField(choices=[('CODE 1', 'CODE 1'), ('CODE 2', 'CODE 2'), ('CODE 3', 'CODE 3'), ('RFI', 'RFI')], default='CODE 1', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('proj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chart.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scurve', models.FileField(blank=True, null=True, upload_to='scurve/%Y/%m/%d')),
                ('progress_p', models.FloatField(blank=True, null=True)),
                ('variance_p', models.FloatField(blank=True, null=True)),
                ('remarks_p', models.CharField(blank=True, max_length=100, null=True)),
                ('mdr_progress_m', models.FloatField(blank=True, null=True)),
                ('variance_m', models.FloatField(blank=True, null=True)),
                ('remarks_m', models.CharField(blank=True, max_length=100, null=True)),
                ('procurement_progress_pp', models.FloatField(blank=True, null=True)),
                ('variance_pp', models.FloatField(blank=True, null=True)),
                ('remarks_pp', models.CharField(blank=True, max_length=100, null=True)),
                ('eng_progress_ep', models.FloatField(blank=True, null=True)),
                ('variance_ep', models.FloatField(blank=True, null=True)),
                ('remarks_ep', models.CharField(blank=True, max_length=100, null=True)),
                ('fab_progress_fp', models.FloatField(blank=True, null=True)),
                ('variance_fp', models.FloatField(blank=True, null=True)),
                ('remarks_fp', models.CharField(blank=True, max_length=100, null=True)),
                ('install_progress_ip', models.FloatField(blank=True, null=True)),
                ('variance_ip', models.FloatField(blank=True, null=True)),
                ('remarks_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('proj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chart.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('due_date_proj', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spool_details', models.CharField(max_length=100)),
                ('drawing_no', models.CharField(max_length=100)),
                ('line_no', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('size1', models.IntegerField(blank=True, null=True)),
                ('sch1', models.IntegerField(blank=True, null=True)),
                ('size2', models.IntegerField(blank=True, null=True)),
                ('sch2', models.IntegerField(blank=True, null=True)),
                ('facing', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('time_due', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('proj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chart.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_s', models.CharField(max_length=100)),
                ('spec_s', models.CharField(max_length=100)),
                ('material_s', models.CharField(max_length=100)),
                ('rating_s', models.CharField(blank=True, max_length=100, null=True)),
                ('size1_s', models.IntegerField(blank=True, null=True)),
                ('sch1_s', models.IntegerField(blank=True, null=True)),
                ('size2_s', models.IntegerField(blank=True, null=True)),
                ('sch2_s', models.IntegerField(blank=True, null=True)),
                ('facing_s', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subproj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('plan_date', models.DateField(blank=True, null=True)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=75, null=True)),
                ('remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('completed', models.BooleanField(blank=True, null=True)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Proj')),
            ],
        ),
    ]
