# Generated by Django 2.1.5 on 2020-05-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_store_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='qty_s',
        ),
    ]
