# Generated by Django 2.1.5 on 2020-06-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200605_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_contactor',
            new_name='is_contractor',
        ),
    ]
