# Generated by Django 2.1.5 on 2020-05-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_auto_20200513_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='address',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
