# Generated by Django 2.1.5 on 2020-05-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_auto_20200515_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
