# Generated by Django 2.1.5 on 2020-05-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='vendor_name',
            new_name='contract_name',
        ),
    ]
