# Generated by Django 2.1.5 on 2020-05-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectactivity_projectactivityplan_projectactivityplanlog_projectrevisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrevisor',
            name='revisor',
        ),
        migrations.RemoveField(
            model_name='projectrevisor',
            name='schedule',
        ),
        migrations.RenameField(
            model_name='projectactivity',
            old_name='created_by',
            new_name='revisor',
        ),
        migrations.DeleteModel(
            name='ProjectRevisor',
        ),
    ]
