# Generated by Django 2.1.5 on 2020-05-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200524_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivityplan',
            name='plan_year',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
    ]
