# Generated by Django 2.1.5 on 2020-06-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0010_auto_20200515_2149'),
        ('projects', '0008_projectactivityplan_actual_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='images/')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chart.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_description', models.CharField(blank=True, max_length=191, null=True)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('weekly_progress', models.CharField(blank=True, max_length=191, null=True)),
                ('cummlative_progress', models.CharField(blank=True, max_length=191, null=True)),
                ('variance', models.CharField(blank=True, max_length=191, null=True)),
                ('progress_statistic', models.CharField(blank=True, max_length=191, null=True)),
                ('procurement', models.CharField(blank=True, max_length=191, null=True)),
                ('mdr', models.CharField(blank=True, max_length=191, null=True)),
                ('fabrication', models.CharField(blank=True, max_length=191, null=True)),
                ('installation', models.CharField(blank=True, max_length=191, null=True)),
                ('reason_for_variance', models.CharField(blank=True, max_length=191, null=True)),
                ('detailed_progress_for_week', models.CharField(blank=True, max_length=191, null=True)),
                ('planned_progress_for_next_week', models.CharField(blank=True, max_length=191, null=True)),
                ('area_of_concerns', models.CharField(blank=True, max_length=191, null=True)),
            ],
        ),
    ]
