# Generated by Django 2.1.5 on 2020-06-25 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200625_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledocument',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
