# Generated by Django 2.1.5 on 2020-05-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_projectitem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='o_number',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
