# Generated by Django 2.1.5 on 2020-05-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_auto_20200515_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='address',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
