# Generated by Django 2.1.5 on 2020-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0007_schedule_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
