# Generated by Django 2.1.5 on 2020-05-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_projectitem_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
