# Generated by Django 2.1.5 on 2020-05-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0009_projectitem_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='projectitem',
            name='project',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='address',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='receipt_number',
        ),
        migrations.DeleteModel(
            name='ProjectItem',
        ),
    ]
